### ISSUE TITLE
Add API Calls to Corresponding ViewModels

### ISSUE THREAD

**Issue by adesh405** [SwiftwareTeam/swiftware_app#25]

**Comment by emmabyte** [comment]
@adesh405, due to migration to SwiftUI, the anatomy of your API calls will be slightly different, but still not difficult! For now, just go ahead and make sure you have a Playground which can call all of our API endpoints (in the format I sent you earlier today (using Task instead of Dispatch Queue)). Then I will add a new task later for integrating your api calls into the ViewModel. If you have any questions about this, feel free to let me know.
